CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,       
    lang TEXT DEFAULT NULL,
    find_count INTEGER DEFAULT 0,
    find_count_set TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isBanned INTEGER DEFAULT 0
);